//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAppService
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdlStatuses
    {
        public cdlStatuses()
        {
            this.CommunicationMessagesReceptionSent = new HashSet<CommunicationMessagesReceptionSent>();
        }
    
        public int ID { get; set; }
        public int Code { get; set; }
        public string DescriptionCz { get; set; }
        public string DescriptionEng { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual ICollection<CommunicationMessagesReceptionSent> CommunicationMessagesReceptionSent { get; set; }
    }
}
