//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAppService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesReceptionSent
    {
        public CommunicationMessagesReceptionSent()
        {
            this.CommunicationMessagesReceptionConfirmation = new HashSet<CommunicationMessagesReceptionConfirmation>();
            this.CommunicationMessagesReceptionSentItems = new HashSet<CommunicationMessagesReceptionSentItems>();
        }
    
        public int ID { get; set; }
        public int MessageId { get; set; }
        public int MessageType { get; set; }
        public string MessageDescription { get; set; }
        public Nullable<System.DateTime> MessageDateOfShipment { get; set; }
        public int MessageStatusId { get; set; }
        public int HeliosOrderId { get; set; }
        public int ItemSupplierId { get; set; }
        public string ItemSupplierDescription { get; set; }
        public System.DateTime ItemDateOfDelivery { get; set; }
        public bool IsManually { get; set; }
        public Nullable<int> StockId { get; set; }
        public string Notice { get; set; }
        public string RadaDokladu { get; set; }
        public Nullable<int> PoradoveCislo { get; set; }
        public string RadaPlusPorCislo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    
        public virtual cdlMessageTypes cdlMessageTypes { get; set; }
        public virtual cdlStatuses cdlStatuses { get; set; }
        public virtual ICollection<CommunicationMessagesReceptionConfirmation> CommunicationMessagesReceptionConfirmation { get; set; }
        public virtual ICollection<CommunicationMessagesReceptionSentItems> CommunicationMessagesReceptionSentItems { get; set; }
    }
}
