//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenix
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FenixEntities : DbContext
    {
        public FenixEntities()
            : base("name=FenixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppLog> AppLog { get; set; }
        public virtual DbSet<cdlKits> cdlKits { get; set; }
        public virtual DbSet<cdlKitsItems> cdlKitsItems { get; set; }
        public virtual DbSet<cdlMessageTypes> cdlMessageTypes { get; set; }
        public virtual DbSet<cdlReturnValues> cdlReturnValues { get; set; }
        public virtual DbSet<cdlStatuses> cdlStatuses { get; set; }
        public virtual DbSet<CommunicationMessagesReceptionConfirmation> CommunicationMessagesReceptionConfirmation { get; set; }
        public virtual DbSet<CommunicationMessagesShipmentOrdersConfirmation> CommunicationMessagesShipmentOrdersConfirmation { get; set; }
        public virtual DbSet<CommunicationMessagesShipmentOrdersConfirmationItems> CommunicationMessagesShipmentOrdersConfirmationItems { get; set; }
        public virtual DbSet<cdlItemTypes> cdlItemTypes { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsSent> CommunicationMessagesKittingsSent { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsSentItems> CommunicationMessagesKittingsSentItems { get; set; }
        public virtual DbSet<CommunicationMessagesReceptionSent> CommunicationMessagesReceptionSent { get; set; }
        public virtual DbSet<CommunicationMessagesReceptionSentItems> CommunicationMessagesReceptionSentItems { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsApprovalKitsSent> CommunicationMessagesKittingsApprovalKitsSent { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsApprovalKitsSerNumSent> CommunicationMessagesKittingsApprovalKitsSerNumSent { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsApprovalSent> CommunicationMessagesKittingsApprovalSent { get; set; }
        public virtual DbSet<CommunicationMessagesShipmentOrdersSent> CommunicationMessagesShipmentOrdersSent { get; set; }
        public virtual DbSet<CommunicationMessagesShipmentOrdersSentItems> CommunicationMessagesShipmentOrdersSentItems { get; set; }
        public virtual DbSet<cdlItems> cdlItems { get; set; }
        public virtual DbSet<cdlMeasures> cdlMeasures { get; set; }
    
        public virtual int prAppLogWrite(string type, string message, string xmlMessage, Nullable<int> userId, string source, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var xmlMessageParameter = xmlMessage != null ?
                new ObjectParameter("XmlMessage", xmlMessage) :
                new ObjectParameter("XmlMessage", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prAppLogWrite", typeParameter, messageParameter, xmlMessageParameter, userIdParameter, sourceParameter, returnValue, returnMessage);
        }
    
        public virtual int prCMRCins(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCMRCins", par1Parameter, returnValue, returnMessage);
        }
    
        public virtual int prCMRCKins(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCMRCKins", par1Parameter, returnValue, returnMessage);
        }
    
        public virtual int prAppLogWriteNew(string type, string message, string xmlDeclaration, string xmlMessage, Nullable<int> userId, string source, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var xmlDeclarationParameter = xmlDeclaration != null ?
                new ObjectParameter("XmlDeclaration", xmlDeclaration) :
                new ObjectParameter("XmlDeclaration", typeof(string));
    
            var xmlMessageParameter = xmlMessage != null ?
                new ObjectParameter("XmlMessage", xmlMessage) :
                new ObjectParameter("XmlMessage", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prAppLogWriteNew", typeParameter, messageParameter, xmlDeclarationParameter, xmlMessageParameter, userIdParameter, sourceParameter, returnValue, returnMessage);
        }
    
        public virtual int prKiSHCins(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prKiSHCins", par1Parameter, returnValue, returnMessage);
        }
    
        public virtual int prCMReturn(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCMReturn", par1Parameter, returnValue, returnMessage);
        }
    
        public virtual int prGetIntValueFromCounter(string counterName, ObjectParameter newValue)
        {
            var counterNameParameter = counterName != null ?
                new ObjectParameter("CounterName", counterName) :
                new ObjectParameter("CounterName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetIntValueFromCounter", counterNameParameter, newValue);
        }
    
        public virtual int prCdlItemsSetSent(Nullable<int> itemID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCdlItemsSetSent", itemIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prCdlKitsSetSent(Nullable<int> itemID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCdlKitsSetSent", itemIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prKittingsApprovalSetSent(Nullable<int> receptionOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var receptionOrderIDParameter = receptionOrderID.HasValue ?
                new ObjectParameter("ReceptionOrderID", receptionOrderID) :
                new ObjectParameter("ReceptionOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prKittingsApprovalSetSent", receptionOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prKittingsOrderSetSent(Nullable<int> receptionOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var receptionOrderIDParameter = receptionOrderID.HasValue ?
                new ObjectParameter("ReceptionOrderID", receptionOrderID) :
                new ObjectParameter("ReceptionOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prKittingsOrderSetSent", receptionOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prReceptionOrderSetSent(Nullable<int> receptionOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var receptionOrderIDParameter = receptionOrderID.HasValue ?
                new ObjectParameter("ReceptionOrderID", receptionOrderID) :
                new ObjectParameter("ReceptionOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prReceptionOrderSetSent", receptionOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prShipmentOrderSetSent(Nullable<int> receptionOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var receptionOrderIDParameter = receptionOrderID.HasValue ?
                new ObjectParameter("ReceptionOrderID", receptionOrderID) :
                new ObjectParameter("ReceptionOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prShipmentOrderSetSent", receptionOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prRORF1ins(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prRORF1ins", par1Parameter, returnValue, returnMessage);
        }
    
        public virtual int prGetAutomatStatus(ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetAutomatStatus", returnValue, returnMessage);
        }
    
        public virtual int prCMReturnedItem(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCMReturnedItem", par1Parameter, returnValue, returnMessage);
        }
    
        public virtual int prCMReturnedShipment(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCMReturnedShipment", par1Parameter, returnValue, returnMessage);
        }
    
        public virtual int prCMDeleteMessage(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCMDeleteMessage", par1Parameter, returnValue, returnMessage);
        }
    
        public virtual int prCrmOrderC1ins(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCrmOrderC1ins", par1Parameter, returnValue, returnMessage);
        }
    
        public virtual int prCrmOrderC2ins(string par1, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var par1Parameter = par1 != null ?
                new ObjectParameter("par1", par1) :
                new ObjectParameter("par1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCrmOrderC2ins", par1Parameter, returnValue, returnMessage);
        }
    }
}
